### ISSUE TITLE
Plugin review class should fly away

### ISSUE THREAD

**Issue by rmccue** [ryanhellyer/unique-headers#3]
`class-dotorg-plugin-review.php` is pretty :-1:. Any chance of removing it? :)

**Comment by ryanhellyer** [comment]
Sorry. I didn't see your message until now. 

And yes, it CAN be removed. I was hoping people wouldn't mind though :/ I was hoping it would be a good way to get more plugin reviews.

Do you think it would be okay for me to provide a constant which would stop the plugin review class from loading? Or do you think I need to kill it entirely?

**Comment by remkus** [comment]
I'm curious why you think it's "pretty 👎" specifically @rmccue.

**Comment by ryanhellyer** [comment]
Sudden brain fart over lunch:

What if I provided a notice on plugin activation which asked for a review, and you could say "bugger off" then. That way clients would not need to see it, as you could block it from their view. Yet I'd still get the benefit of pestering people a week later to write a review for me.

Would that work?

I'm just trying to come up with a solution which doesn't involve removing this. Although if it is annoying you, I will yank it. I don't want my plugins to be thought of like WordPress SEO, with it's plethora of spammy pop-ups.

**Comment by pdewouters** [comment]
Just wanted to add my feedback. But first, thanks for making the plugin available :)
It's a bit too eager maybe? After one second
<img width="836" alt="screenshot 2015-12-10 11 58 36" src="https://cloud.githubusercontent.com/assets/30460/11715038/8bde9aca-9f36-11e5-8bd3-229cd60be5f9.png">

**Comment by rmccue** [comment]
FWIW, not a fan of this because it's kinda just cruft, and annoying users too. I similarly dislike iOS apps that ask me to review them :)

**Comment by ryanhellyer** [comment]
@pdewouters it's meant to be after one week. I have no idea how it would be showing 1 second for you. I'll look into that and fix whatever is causing it. Thanks for reporting it :)

@rmccue The problem is, it's working quite well at generating reviews :/ I might ask Jeff or Sara if they're interested in writing about this issue, and perhaps we can get some community feedback on it. In the mean time I'm holding off on sticking it in any other plugins.

**Comment by ryanhellyer** [comment]
I've adjusted this so that it only shows on the main plugins page, so will hopefully be less annoying to people.
